# Generated by Django 5.2.6 on 2026-01-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fare',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fare',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fare',
            name='surcharge_per_km',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fare',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Precio final calculado', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fare',
            name='currency',
            field=models.CharField(default='COP', max_length=3),
        ),
    ]
