# Generated by Django 5.2.6 on 2026-01-21 16:31

import apps.vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'Car'), ('MOTORCYCLE', 'Motorcycle')], default='CAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(help_text='Formato: ABC123 (carro) o ABC12D (moto)', max_length=6, unique=True, validators=[apps.vehicles.models.validate_license_plate]),
        ),
    ]
