# Generated by Django 5.2.6 on 2026-01-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_remove_vehicle_driver_vehicle_drivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
