# Generated by Django 5.2.6 on 2026-01-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indica si este vehículo está activo para el conductor'),
        ),
    ]
