# Generated by Django 5.2.6 on 2026-01-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_destination_location_trip_origin_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'Car'), ('MOTORCYCLE', 'Motorcycle')], default='CAR', max_length=20),
        ),
    ]
