# Generated by Django 5.2.6 on 2026-01-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
