# Generated by Django 5.2.6 on 2026-01-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_destination_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='origin_address',
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='service_type',
            field=models.CharField(choices=[('TRIP', 'Trip'), ('DELIVERY', 'Delivery')], default='TRIP', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination_address',
            field=models.CharField(max_length=255),
        ),
    ]
