# Generated by Django 5.2.9 on 2026-01-21 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('trips', '0005_remove_trip_origin_address_trip_pickup_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='service_type',
            field=models.CharField(choices=[('TRIP', 'Viaje'), ('DELIVERY', 'Domicilio')], default='TRIP', max_length=20),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=5, help_text='Calificación de 0 a 5 estrellas')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rated_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='drivers.driverprofile')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='trips.trip')),
            ],
        ),
    ]
