# Generated by Django 5.2.6 on 2026-01-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_trip_service_type_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio estimado ofrecido por el cliente', max_digits=10),
        ),
    ]
