# Generated by Django 5.2.6 on 2026-01-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_trip_estimated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio estimado ofrecido por el cliente', max_digits=12),
        ),
    ]
